import os
BOT_TOKEN = "7815817538:AAFF1QN_RIMga714dsaV2v5q96NKJXqmXWQ"



MONGO_URI = os.getenv("MONGO_URI", "mongodb://localhost:27017/")
DB_NAME = "teacherbot"

COLLECTION_NAME_DISCIPLINES = "disciplines"
COLLECTION_NAME_COURSES = "courses"
COLLECTION_NAME_TOPICS = "topics"
COLLECTION_NAME_LESSONS = "lessons"
COLLECTION_NAME_TESTS = "tests"
COLLECTION_NAME_USERS = "users"
COLLECTION_NAME_ANSWERS = "answers"